# Generated by Django 2.0.6 on 2018-07-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='id',
        ),
        migrations.AddField(
            model_name='subscription',
            name='hashid',
            field=models.CharField(default=0, max_length=11, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
