# Generated by Django 2.0.6 on 2018-07-02 23:22

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20180702_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='created_at2',
        ),
        migrations.AddField(
            model_name='subscription',
            name='teste_id',
            field=hashid_field.field.HashidField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', default='1234567', min_length=7),
        ),
    ]
