# Generated by Django 2.0.6 on 2018-07-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_auto_20180702_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='teste_id',
        ),
        migrations.AddField(
            model_name='subscription',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
