# Generated by Django 2.0.6 on 2018-07-02 23:40

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_auto_20180702_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='id',
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_id',
            field=hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', default=1, min_length=7, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
